const archiveExtraIdeas = [
  { href: 'moneyc.html', title: 'Why Do Currencies Gain and Lose Value?', category: 'economics', preview: 'The economic forces that determine the value of money around the world.' },
  { href: 'microplastics.html', title: 'Impact of Microplastics on Aquatic Food Webs', category: 'biology', preview: 'How microplastics move through aquatic ecosystems, from microscopic organisms to fish and other animals.' },
  { href: 'hall.html', title: 'The Monty Hall Problem', category: 'math', preview: 'A counterintuitive puzzle that challenges our understanding of probability.' },
  { href: 'regeneration.html', title: 'Hidden Regeneration', category: 'biology', preview: 'The biological mystery behind our limited ability to regenerate body parts.' },
  { href: 'knot.html', title: 'Numerical Analysis', category: 'math', preview: 'How algorithms, approximations, and computational methods find solutions to real-world problems.' },
  { href: 'water.html', title: 'How Does Climate Change Affect Freshwater Availability?', category: 'geography', preview: 'How rising temperatures and changing rainfall reshape freshwater supplies around the world.' },
  { href: 'acoustic.html', title: 'Acoustic Resonance: Humidity and the Speed of Sound', category: 'physics', preview: 'How air moisture affects the speed of sound through controlled measurements.' },
  { href: 'mandela.html', title: 'The Mandela Effect', category: 'psychology', preview: 'Why large groups of people can share the same false memory.' },
  { href: 'goosebumps.html', title: 'Why Do We Get Goosebumps?', category: 'neuroscience', preview: 'Why skin develops tiny bumps when we are cold, frightened, excited, or deeply moved.' },
  { href: 'capitalism.html', title: 'Capitalism', category: 'economics', preview: 'The economic system that transformed how people produce, trade, and build wealth.' },
  { href: 'neuroplasticity1.html', title: 'Neuroplasticity', category: 'neuroscience', preview: 'The surprising science behind why your recorded voice sounds so unfamiliar.' },
  { href: 'haiti.html', title: 'The Haitian Revolution', category: 'history', preview: 'How an uprising transformed a French colony into an independent nation.' },
  { href: 'procastinate.html', title: 'Why Do We Procrastinate?', category: 'psychology', preview: 'Why people delay important tasks and how emotions often drive procrastination.' },
  { href: 'mathai.html', title: 'How Does Artificial Intelligence Use Mathematics?', category: 'math', preview: 'How equations, statistics, and algorithms enable machines to learn and make predictions.' },
  { href: 'cern.html', title: 'Inside CERN: Heart of Matter', category: 'physics', preview: "The world's most powerful machines for exploring the building blocks of matter." },
  { href: 'puffyeyes.html', title: 'Why Eyes Get Puffy', category: 'biology', preview: 'How fluid retention, sleep position, and natural processes can cause swollen eyes.' },
  { href: 'doubleslit.html', title: 'The Double Slit Experiment', category: 'physics', preview: 'The famous experiment that challenged our understanding of reality.' },
  { href: 'genedogma.html', title: 'Gene Theory & The Central Dogma', category: 'biology', preview: 'How hereditary information flows from DNA to RNA to protein.' },
  { href: 'assamcalculus.html', title: 'Assembly Calculus', category: 'neuroscience', preview: 'A framework for how connected neurons may combine and manipulate information.' },
  { href: 'rationality.html', title: 'Induction Rationality', category: 'philosophy', preview: 'How we draw general conclusions from limited observations every day.' },
  { href: 'biohack.html', title: 'Biohacking', category: 'biology', preview: 'The science of optimizing your body and mind through lifestyle and technology.' },
  { href: 'bronzeage.html', title: 'The Bronze Age Collapse', category: 'history', preview: 'The complex forces that may have brought an interconnected ancient world to its knees.' },
  { href: 'evolution.html', title: 'Evolution', category: 'biology', preview: 'How natural selection, genetic variation, and environmental pressures drive change in species.' },
  { href: 'ownvoice.html', title: 'Why We Hate Our Voices', category: 'neuroscience', preview: 'The surprising science behind why your recorded voice sounds so unfamiliar.' },
  { href: 'tunneling.html', title: 'Quantum Tunneling', category: 'physics', preview: 'The quantum phenomenon that lets particles pass through seemingly impossible barriers.' },
  { href: 'commons.html', title: 'Tragedy of the Commons', category: 'economics', preview: "Why shared resources are often overused despite everyone's best interests." },
  { href: 'forget.html', title: 'Why Do We Forget Things?', category: 'neuroscience', preview: 'Why memory fades and how the brain forgets information.' },
  { href: 'satellite.html', title: 'Satellite Data: Nighttime Lights and Economic Activity', category: 'geography', preview: 'How satellite imagery helps researchers study economic activity, urbanization, and light pollution.' },
  { href: 'monetarism.html', title: 'Monetarism', category: 'economics', preview: 'How the money supply can influence inflation, prices, and economic stability.' },
  { href: 'gametheory.html', title: 'Game Theory of Everyday Life', category: 'economics', preview: 'How strategic thinking shapes the choices we make every day.' },
  { href: 'dilation.html', title: 'Time Dilation', category: 'physics', preview: 'Why time flows differently at extreme speeds and in strong gravity.' },
  { href: 'argentina.html', title: 'Geography of Argentina', category: 'geography', preview: 'From the Andes and Pampas to Patagonia’s glaciers.' },
  { href: 'paradoxe.html', title: 'The Paradox of Choice', category: 'psychology', preview: 'How having too many choices influences decisions and satisfaction.' },
  { href: 'dissonance.html', title: 'Cognitive Dissonance', category: 'psychology', preview: 'The mental discomfort of holding conflicting beliefs or behaviors.' },
  { href: 'mprimes.html', title: 'Mersenne Primes', category: 'math', preview: 'Rare prime numbers hidden within a remarkably simple mathematical formula.' },
  { href: 'billingual.html', title: 'The Bilingual Brain', category: 'neuroscience', preview: 'How speaking two languages reshapes the brain and enhances cognition.' },
  { href: 'timezone.html', title: 'Invention of Time Zones', category: 'history', preview: 'How time zones keep the world connected, from Greenwich to every corner of the planet.' },
  { href: 'feudalism.html', title: 'Feudalism', category: 'history', preview: 'How land, loyalty, and obligations shaped medieval European society.' },
  { href: 'intelligence.html', title: 'Illusion of AI Sentience', category: 'philosophy', preview: 'Questioning fundamental truths and values, and what it means to be human.' },
  { href: 'bislands.html', title: 'Birth of Volcanic Islands', category: 'geography', preview: 'The geological forces that build islands from the ocean floor.' },
  { href: 'dejavu.html', title: 'Why Do We Feel Déjà Vu?', category: 'neuroscience', preview: 'A fleeting, false sense of familiarity caused by memory misfires.' },
  { href: 'rainbow.html', title: 'Physics Behind the Colours', category: 'physics', preview: 'The interaction of light and water that creates a rainbow.' },
  { href: 'firering.html', title: 'The Ring of Fire', category: 'geography', preview: "The vast zone where most of Earth's earthquakes and volcanoes occur." },
  { href: 'jellyfish.html', title: 'Immortal Jellyfish', category: 'biology', preview: 'The extraordinary jellyfish that can reverse its own aging process.' },
  { href: 'solipsism.html', title: 'Solipsism', category: 'philosophy', preview: 'The philosophical idea that only your own mind can be known to exist.' },
  { href: 'ecuation.html', title: "E = mc²: Einstein's Most Famous Equation", category: 'physics', preview: 'The profound relationship between mass, energy, and the universe.' },
  { href: 'stress.html', title: 'Sleep, Stress, and the Science of Decision-Making', category: 'psychology', preview: 'How sleep and stress influence attention, memory, emotions, and everyday decisions.' },
  { href: 'dance.html', title: 'Dancing Plague of 1518', category: 'history', preview: 'A mysterious epidemic that compelled hundreds to dance uncontrollably.' },
  { href: 'inflation.html', title: 'Why Do Prices Rise Over Time?', category: 'economics', preview: 'Why creating more money does not automatically create wealth and can lead to inflation.' },
  { href: 'idealism.html', title: 'Idealism', category: 'philosophy', preview: 'Is reality independent of the mind, or does consciousness shape what we call real?' },
  { href: 'secretcode.html', title: "Nature's Secret Code", category: 'math', preview: 'The hidden mathematical patterns woven throughout the natural world.' },
  { href: 'barnum.html', title: 'The Barnum Effect', category: 'psychology', preview: 'Why generic statements can seem uniquely accurate.' },
  { href: 'fourcolours.html', title: 'The Four-Color Theorem', category: 'math', preview: 'The complex mathematical problem behind coloring any map with just four colors.' },
  { href: 'solarcells.html', title: 'Perovskite Solar Cells', category: 'physics', preview: 'How perovskite materials convert sunlight into electricity and promise new solar technology.' },
  { href: 'migrationb.html', title: 'Mystery of Bird Migration', category: 'biology', preview: 'How birds navigate thousands of kilometers with astonishing precision.' },
  { href: 'kruger.html', title: 'The Dunning-Kruger Effect', category: 'psychology', preview: 'Why people with less knowledge often overestimate their abilities.' },
  { href: 'aging.html', title: 'The Somatic Mutation Theory of Aging', category: 'biology', preview: 'How mutations accumulating in somatic cells may contribute to aging.' },
  { href: 'keynesian.html', title: 'Keynesian Economics & Macroeconomic Theories', category: 'economics', preview: 'How competing theories explain growth, unemployment, inflation, and economic crises.' },
  { href: 'modelt.html', title: 'Model Theory', category: 'math', preview: 'How formal languages, axioms, and mathematical structures relate to one another.' },
  { href: 'sargasso.html', title: 'The Sargasso Sea', category: 'geography', preview: 'A unique ocean region defined by currents instead of land.' },
  { href: 'landlocked.html', title: 'Why Are Some Countries Completely Landlocked?', category: 'geography', preview: 'How geography, history, and political borders shaped countries without access to the sea.' },
  { href: 'fjords.html', title: 'How Are Fjords Created?', category: 'geography', preview: 'The geological forces behind deep, narrow coastal valleys.' },
  { href: 'fractals.html', title: 'Fractals', category: 'math', preview: 'The mesmerizing mathematics behind self-repeating patterns in nature.' },
  { href: 'pascalslaw.html', title: "Pascal's Law", category: 'physics', preview: 'A fundamental principle that explains how pressure behaves in confined fluids.' },
  { href: 'sound.html', title: 'Journey of Sound', category: 'physics', preview: 'How vibrations travel through the air and become sounds our brain interprets.' },
  { href: 'integrated.html', title: 'The Integrated Information Theory of Consciousness', category: 'neuroscience', preview: 'A theory that proposes consciousness arises from integrated information.' },
  { href: 'darkuniverse.html', title: 'Dark Matter vs. Dark Energy', category: 'physics', preview: "The cosmic mystery behind the universe's hidden mass and accelerating expansion." },
  { href: 'rome.html', title: 'Fall of Rome: Myth or Fact', category: 'history', preview: "One of history's greatest collapses, surrounded by myths and enduring debates." },
  { href: 'existentialism.html', title: 'Existentialism', category: 'philosophy', preview: 'How existentialist philosophers confronted freedom, responsibility, meaning, and authenticity.' },
  { href: 'slave.html', title: 'The Abolition Movement', category: 'history', preview: 'How activists and ordinary citizens challenged slavery in the United States from 1830 to 1865.' },
  { href: 'maya.html', title: 'The Maya Civilization', category: 'history', preview: 'Environmental, political, and social factors behind the decline of many Maya cities.' },
  { href: 'bystander.html', title: 'The Bystander Effect', category: 'psychology', preview: 'Why people may be less likely to help when others are present.' },
  { href: 'absurd.html', title: 'Absurdism', category: 'philosophy', preview: "The philosophy of humanity's search for meaning in a seemingly meaningless universe." },
  { href: 'doppler.html', title: 'The Doppler Effect', category: 'physics', preview: 'How motion changes the frequency of waves we perceive.' },
  { href: 'emuwar.html', title: 'The Great Emu War', category: 'history', preview: 'The bizarre conflict where thousands of emus outmatched the Australian military.' },
  { href: 'flow.html', title: 'The Flow State', category: 'psychology', preview: 'The mental state where focus, performance, and enjoyment reach their peak.' },
  { href: 'hot.html', title: 'Higher-Order Theory (HOT)', category: 'neuroscience', preview: 'The proposal that consciousness may depend on the brain representing its own mental states.' },
  { href: 'simulation.html', title: 'Simulation Theory', category: 'philosophy', preview: 'A philosophical idea that questions the nature of the reality we experience.' },
  { href: 'lostcolony.html', title: 'The Lost Colony of Roanoke', category: 'history', preview: "The enduring mystery of England's first vanished American colony." },
  { href: 'ghosttown.html', title: 'Ghost Towns', category: 'geography', preview: 'The fascinating stories behind cities that were left deserted.' },
  { href: 'intelligence.html', title: 'Ship of Theseus', category: 'philosophy', preview: 'A timeless paradox that challenges the nature of identity and change.' },
  { href: 'soil.html', title: 'Global Soil Erosion', category: 'geography', preview: "How wind, water, deforestation, and agriculture threaten Earth's essential soil." },
  { href: 'mechanism.html', title: 'Antikythera Mechanism', category: 'history', preview: 'The ancient machine that reveals how advanced Greek technology really was.' },
  { href: 'yawn.html', title: 'The Mystery of the Yawn', category: 'neuroscience', preview: 'An involuntary reflex that spreads between people, yet remains surprisingly mysterious.' },
  { href: 'grapht.html', title: 'Graph Theory', category: 'math', preview: 'How networks of points and connections reveal patterns in transportation, society, and computing.' },
  { href: 'circulare.html', title: 'The Circular Economy', category: 'economics', preview: 'A sustainable economic model that reduces waste by reusing resources.' },
  { href: 'russia.html', title: 'The Fall of the Romanovs', category: 'history', preview: 'The dramatic fall of the Romanov dynasty during the Russian Revolution.' },
  { href: 'gaia.html', title: 'The Gaia Hypothesis', category: 'biology', preview: "The idea that living organisms and their environment interact to influence Earth's conditions." },
  { href: 'neoclassical.html', title: 'Neoclassical Economics', category: 'economics', preview: 'How incentives, scarcity, and supply and demand explain how markets allocate resources.' },
  { href: 'pitagoras.html', title: 'The Pythagorean Theorem', category: 'math', preview: "How a famous equation connects the sides of right triangles and the mystery of √2." },
  { href: 'numericalan.html', title: 'Knot Theory', category: 'math', preview: 'How knot theory studies curves in three-dimensional space and helps scientists understand DNA.' },
  { href: 'voynich.html', title: 'Voynich Manuscript', category: 'history', preview: 'The mysterious book that no one has been able to decipher.' },
  { href: 'trolley.html', title: 'The Trolley Problem', category: 'philosophy', preview: 'The famous ethical dilemma that challenges our moral instincts.' },
  { href: 'shortvideos.html', title: 'Short-Form Videos and the Brain', category: 'psychology', preview: 'How rapidly changing content may influence attention, reward, memory, and habits.' },
  { href: 'bankrun.html', title: 'Why Do Bank Runs Happen?', category: 'economics', preview: 'How fear can cause many people to withdraw their money from a bank at once.' },
  { href: 'physicala.html', title: 'Brains & Physical Activity', category: 'neuroscience', preview: 'How physical activity strengthens the brain and boosts cognitive performance.' },
  { href: 'bigmac.html', title: 'Big Mac Index', category: 'economics', preview: 'A surprisingly simple way to compare the value of currencies around the world.' },
  { href: 'stoicism.html', title: 'Stoicism', category: 'philosophy', preview: 'A practical approach to uncertainty, emotions, and focusing on what we can control.' },
  { href: 'epigenetics.html', title: 'Epigenetics Beyond DNA', category: 'biology', preview: 'How lifestyle and environment can shape gene activity.' },
  { href: 'bmusic.html', title: 'Memory and Music', category: 'neuroscience', preview: 'Why certain songs can bring back vivid memories, emotions, and moments from our past.' },
  { href: 'machine.html', title: 'The Experience Machine', category: 'philosophy', preview: 'Would you choose a perfect virtual life over reality?' },
  { href: 'impostor.html', title: 'The Impostor Syndrome', category: 'psychology', preview: 'The persistent feeling of being a fraud despite evidence of success.' },
  { href: 'calendar.html', title: 'Mastering the Calendar: Calculating the Weekday', category: 'math', preview: 'The hidden patterns and mathematical techniques behind calendars.' },
  { href: 'chaos.html', title: 'Chaos Theory', category: 'math', preview: 'Why simple rules can produce astonishingly chaotic behavior.' },
  { href: 'paradox.html', title: 'Banach-Tarski Paradox', category: 'math', preview: 'A mathematical paradox in which one sphere can be decomposed and reassembled into two identical copies.' },
  { href: 'habits.html', title: 'Habit Formation and the Brain', category: 'psychology', preview: 'How repetition, reward, and neural learning can make actions automatic.' },
  { href: 'subcons.html', title: 'Subconscious Conditioning', category: 'psychology', preview: 'How implicit associations and environmental cues can shape attention and behavior.' },
  { href: 'appendix.html', title: 'The Appendix: Risk or Refuge?', category: 'biology', preview: 'The appendix as an immune aid and microbial refuge, rather than a useless vestige.' }
];